### ISSUE TITLE
The Text blinker is coming over the validation popup message in IOS devices, its being able to enter the data in background without closing the popup

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#12]
The Text blinker is coming over the validation popup message in IOS devices, its being able to enter the data in background without closing the popup

Steps to Reproduce:
1. Go to Application 
2. Make the validation popup with entering wrong data in fields

**Comment by mustafazaki** [comment]
not replecating on iphone 5 and galaxy s3
