### ISSUE TITLE
The Space and character should not work in below listed fields in  create new online user page and reset password page 1.	Account number 2.	Pin 3.	Mobile number 4.	Tag number

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#13]
The Space and character should not work in below listed fields in 
create new online user page and reset password page
1.  Account number
2.  Pin
3.  Mobile number
4.  Tag number

Steps to Reproduce:
1. Go to Application 
2. Go to create new online user page or reset password page

**Comment by mustafazaki** [comment]
Ibad please add class "numberonly" or change "input type to number" on those input which should not accept alphabets
