### ISSUE TITLE
Should provide the Header “New Account“ in Create new online user page

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#18]
![image](https://cloud.githubusercontent.com/assets/1317442/5943231/92e034bc-a736-11e4-8467-11fec12b8fa6.png)

Should provide the Header “New Account“ in Create new online user page

Steps to Reproduce:
1. Go to Application 
2. Click on new online user

Devices: Samsung Note 3-
Google chrome

**Comment by umayr** [comment]
Fixed as it can be seen [here](http://cubicflux.trickip.net:2089/Salik/User/RegisterUser).
