### ISSUE TITLE
 Previously entered data is coming in text boxes once clear the filed by backslash / delete button from keyboard after coming the same page after click on “OK” from error validation popup after the next button

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#19]
![image](https://cloud.githubusercontent.com/assets/1317442/5943238/ac99ae42-a736-11e4-9df4-57da6ae8a8e5.png)

Previously entered data is coming in text boxes once clear the filed by backslash / delete button from keyboard after coming the same page after click on “OK” from error validation popup after the next button

Steps to Reproduce:
1. Go to Application 
2. Make the error entry in fields
3. Click on Next button

Devices: Samsung Note 3-
Google chrome

**Comment by zubairahmed-ai** [comment]
@mustafazaki can you please check

**Comment by mustafazaki** [comment]
its a default behavior of browser can't be fixed
