### ISSUE TITLE
The save functionality is not working or not providing validation  message when entered new password filed is 4 digit

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#21]
![image](https://cloud.githubusercontent.com/assets/1317442/5943309/4c80042e-a737-11e4-8095-0d0ab7cf17b7.png)

The save functionality is not working or not providing validation 
message when entered new password filed is 4 digit

Steps to Reproduce:
1. Go to Application 
2. Go to change password

Devices: Samsung Note 3-
Google chrome

**Comment by ghost** [comment]
There is already a server-side validation on it that's preventing it to change the password when the user enters new password containing less than 6 characters. We need client-side validation on it, assigning it to @mustafazaki
