### ISSUE TITLE
The password is being successfully changing even when enter the  wrong current password

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#24]
![image](https://cloud.githubusercontent.com/assets/1317442/5943346/97dee764-a737-11e4-8f3a-02dc0209fc24.png)

The password is being successfully changing even when enter the 
wrong current password

Steps to Reproduce:
1. Go to Application 
2. Go to Change password field

Devices: Samsung Note 3-
Google chrome

**Comment by umayr** [comment]
Fixed with `f7a77ea6742475b16301463b8f5f4e9cd6994dc8`

**To view:** `git show f7a77ea`
