### ISSUE TITLE
The sign in icon should be bigger as similar like other ion in menu

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#28]
![image](https://cloud.githubusercontent.com/assets/1317442/5943387/eadb155a-a737-11e4-8e30-d9e6a2eddf44.png)

The sign in icon should be bigger as similar like other ion in menu

Steps to Reproduce:
1. Go to Application 
2. Go to Home menu

Devices: Samsung Note 3-
Google chrome

**Comment by mustafazaki** [comment]
@mibaigg Please upload "Views/Home/Index.cshtml" I update it and commit it on SalikOnGit repo
