### ISSUE TITLE
 Should not accept the character in mobile number field in Feed    back page

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#3]
![image](https://cloud.githubusercontent.com/assets/1317442/5943056/26e33fd0-a735-11e4-8e62-c39da0c56af6.png)

Should not accept the character in mobile number field in Feed    back page

Steps to Reproduce :
1.  Go to Application
2.  Go to new online user page

**Comment by mustafazaki** [comment]
Ibad please add class "numberonly" or change "input type to number" on those input which should not accept alphabets
