### ISSUE TITLE
The “sign in” icon/Logo should be smaller as similar icons in drop down menu

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#31]
![image](https://cloud.githubusercontent.com/assets/1317442/5943422/399804dc-a738-11e4-88c0-5287ca2f70e9.png)

The “sign in” icon/Logo should be smaller as similar icons in drop down menu

Steps to Reproduce:
1. Go to Application 
2. Click on drop down menu

Devices: Samsung Note 3-
Google chrome

**Comment by mustafazaki** [comment]
@mibaigg please upload "View/Shared/_NavMenu-PreLogin.cshtml"
