### ISSUE TITLE
Should not show the drop down menus when swipe from pages

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#36]
Should not show the drop down menus when swipe from pages. Should show the drop down only when click on drop down menu tag at center top of application

![image](https://cloud.githubusercontent.com/assets/1317442/6525425/dc98682c-c41e-11e4-889c-eecaf1a1a796.png)

**Comment by zubairahmed-ai** [comment]
1.  Go to Application
2.  Swipe the page to down

**Comment by mustafazaki** [comment]
its a default behavior of browser and cant be fixed
