### ISSUE TITLE
Application icons and designs are blurred in web application

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#37]
Application icons and designs are blurred in web application, Info icon, Drop down menu dragger and Notification are blurred or icons are different Please update the icons as shown in screen short

![design issue](https://cloud.githubusercontent.com/assets/1317442/6525476/3d12b95a-c41f-11e4-9363-cc98fe426410.jpg)

**Comment by mustafazaki** [comment]
need svg icons they are using retina displays

**Comment by zubairahmed-ai** [comment]
ok let me ask them
