### ISSUE TITLE
Should not accept the character in account number, and it should restrict to 8 digit

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#38]
Should not accept the character in account number, and it should restrict to 8 digit
Steps To Reproduce  
1. Go to Application
2. Go to new online user page

**Comment by mustafazaki** [comment]
add (maxlength) attribute and class (number) if field type is text 
if field type is number then add these attribytes (oninput="maxLengthCheck(this)" maxlength="12")
