### ISSUE TITLE
 Add phone number button is missing in view profile

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#39]
Add phone number button is missing in view profile
Steps To Reproduce  
1. Go to application
2. Go to view Profile

**Comment by umayr** [comment]
There is an **Add Number** button if you go to [http://cubicflux.trickip.net:2089/Salik/User/Profile](http://cubicflux.trickip.net:2089/Salik/User/Profile) after login. And in the android build, its an icon rather than text _Add Number_ and the icon is not available in `Content/Images` folder.

**Comment by zubairahmed-ai** [comment]
@mustafazaki can you please check?

**Comment by mustafazaki** [comment]
link is not working

**Comment by zubairahmed-ai** [comment]
check screenshots in your email @mustafazaki

**Comment by umayr** [comment]
@mustafazaki Login into app then go the link.

**Comment by mustafazaki** [comment]
done and pushed
