### ISSUE TITLE
Should be clear the field in forgot password page instead of putting zero  as default 

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#4]
![image](https://cloud.githubusercontent.com/assets/1317442/5943071/561f635a-a735-11e4-9442-cb99c12aa719.png)

Should be clear the field in forgot password page instead of putting zero 
as default 

Steps to Reproduce :
1.  Go to Application
2.  Go to new online user page

**Comment by ghost** [comment]
@mustafazaki this is not a server-side issue, it will be done from client-side.

**Comment by mustafazaki** [comment]
@mibaigg value of input is 0 by default please remove it
