### ISSUE TITLE
The key board is not being to hide back once active

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#45]
The key board is not being to hide back once active in Balance top up screen safari- iPad

**Comment by zubairahmed-ai** [comment]
Safari- iPad

**Comment by mustafazaki** [comment]
its working fine on my ipad

**Comment by zubairahmed-ai** [comment]
make sure it is deployed

**Comment by mustafazaki** [comment]
yes i checked it on 2089 link
