### ISSUE TITLE
 should not bounce horizontally and vertically in home screen when click on notification button

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#46]
should not bounce horizontally and vertically in home screen when click on notification button - ipad Safari

**Comment by zubairahmed-ai** [comment]
Mustufa here you go

Steps to Reproduce:

Step 1. taps on Notification 
Step 2. swipe screen in safari (IOS)
ipad Safari
-- Refer screen short for More info about the issue--

![image](https://cloud.githubusercontent.com/assets/1317442/6546211/b0f4a508-c5c4-11e4-855d-70a29d645a3a.png)

![image](https://cloud.githubusercontent.com/assets/1317442/6546213/b67ff4aa-c5c4-11e4-92c3-577b87297af6.png)

**Comment by mustafazaki** [comment]
update default.js and style.css
