### ISSUE TITLE
Should be capitalize first letter of all the Validation messages

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#5]
![image](https://cloud.githubusercontent.com/assets/1317442/5943095/8af40aae-a735-11e4-95b3-f3e5959fdae6.png)

Should be capitalize first letter of all the Validation messages

Steps to Reproduce:
1.  Go to Application
2.  Go to new online user page

**Comment by mustafazaki** [comment]
Ibad will do this
