### ISSUE TITLE
Should not accept the character in Pin filed, and it should restrict  to 4 digit in feedback and new online user screen

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#58]
Steps to Reproduce:
1.  Go to Application
2.  Go to forgot password

**Comment by mustafazaki** [comment]
Ibad please add class "numberonly" or change "input type to number" on those input which should not accept alphabets

**Comment by mustafazaki** [comment]
add (maxlength) attribute and class (number) if field type is text 
if field type is number then add these attribytes (oninput="maxLengthCheck(this)" maxlength="12")

**Comment by ghost** [comment]
@Zubair, there is no Pin field on Feedback page, please confirm.

**Comment by zubairahmed-ai** [comment]
where ever there is pin field restrict it
