### ISSUE TITLE
PIN number should be restricted to 4 digit and should not visible the pin number.

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#61]
PIN number should be restricted to 4 digit and should not visible the pin number. (Eg. Show as dot : PIN .... ) in Pre login Balance topup

**Comment by mustafazaki** [comment]
add (maxlength) attribute and class (number) if field type is text 
if field type is number then add these attribytes (oninput="maxLengthCheck(this)" maxlength="12")

**Comment by ghost** [comment]
@mustafazaki maxlength property doesn't seem to be working, please look into it.

**Comment by ghost** [comment]
Its now working, the js needed to be updated.
